---
- name: Configure OpenShift LDAP authentication and group sync against IDM
  hosts: aws_metal
  gather_facts: true
  vars_files:
    - ../../vars/global/execution_environment.yml
    - ../../vars/global/mirror_content.yml
    - ../../vars/global/lab_switch_ports.yml
    - ../../vars/guests/idm_vm.yml
    - ../../vars/cluster/openshift_install_cluster.yml
    - ../../vars/day2/openshift_ldap_auth.yml
  roles:
    - role: openshift_post_install_ldap_auth
